#Configuration file
#Avoid hardcoding passwords. Use a YAML file.
mt5:
  login: 12345678          # Your MT5 account number
  password: "YourPassword"
  server: "Broker-Server"
  path: "C:/Program Files/MetaTrader 5/terminal64.exe"

bot_settings:
  symbols: ["EURUSD", "GBPUSD", "XAUUSD"]
  timeframe: "TIMEFRAME_M15"
  magic_number: 123456
  lot_size: 0.1

telegram:
  token: "your_bot_token"
  chat_id: "your_chat_id"